### ISSUE TITLE
Generate list of sensors

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#12]

**Comment by spsmichi** [comment]
@Michi

**Comment by StudentSchnitzel** [comment]
Servus Thomas, kannst du mir diesen task zuweisen? Selbst geht das nicht....


Typ | Modell | Funktion | Implementierung | Notizen
-- | -- | -- | -- | --
Drehzahlsensor |   | Raddrehzahl | Erfolgreich | Pflicht
Flame Detection | Hyperion Arduino Compatible Flame Detection   Sensor | Flame-Detection | Erfolgreich | Pflicht für “Fire-Team”
Ultraschallsensor | HC-SR04 | Abstandsmessung | Erfolgreich | Pflicht (1x mit Servo, oder 3x mit
Servo | SM-2309S | Bewegen | Erfolgreich | Pflicht bei 1x Ultraschall
Kamera | Raspberry Pi Camera Module | Bild à Objekterkennung? | Erfolgreich | Optional
Gyro | Adafruit2472 | Orientierung | TBC | Optional
Infrarot | SEN0206, aushttps://www.dfrobot.com/product-1495.html | Temperatur | TBC | Optional
Lautsprecher |   |   | Erfolgreich | Aus Arduino kit
LIDAR |   | Abstandsmessung | TBC |  
RGB LED Modul | KY-016 | Anzeige | TBC | Optional

**Comment by Denkschmied** [comment]
Kannst du die Tabelle ins Wiki verschieben?

**Comment by StudentSchnitzel** [comment]
@Denkschmied 
Passt das so? https://github.com/Denkschmied/fire-and-ice/wiki/List-of-Sensors 
Ich konnte den wiki Eintrag leider nicht mit dem issue Verknüpfen

**Comment by Denkschmied** [comment]
Schaut gut aus :-)

**Comment by MatteoOPD** [comment]
Welche der Sensoren sollten jetzt zwingend ins Fahrzeug integriert werden? Ich bräuchte die Information um die Konstruktion weiterzubringen. 
@mausausdruck1 / @StudentSchnitzel: Könnt ihr hier was sagen?

**Comment by mausausdruck1** [comment]
2 x Speedsensor LM393 an den Achsen (oder etwas anderes, womit du sicher herausfindest, wo du bist)
mind. 1 x Ultraschall
Kamera
ggf RFID-Leser am Boden

**Comment by MatteoOPD** [comment]
+ Flame-Sensor für das Fire-Team, oder?

**Comment by MatteoOPD** [comment]
> Servus Thomas, kannst du mir diesen task zuweisen? Selbst geht das nicht....
> 
> Typ	Modell	Funktion	Implementierung	Notizen
> Drehzahlsensor	 	Raddrehzahl	Erfolgreich	Pflicht
> Flame Detection	Hyperion Arduino Compatible Flame Detection Sensor	Flame-Detection	Erfolgreich	Pflicht für “Fire-Team”
> Ultraschallsensor	HC-SR04	Abstandsmessung	Erfolgreich	Pflicht (1x mit Servo, oder 3x mit
> Servo	SM-2309S	Bewegen	Erfolgreich	Pflicht bei 1x Ultraschall
> Kamera	Raspberry Pi Camera Module	Bild à Objekterkennung?	Erfolgreich	Optional
> Gyro	Adafruit2472	Orientierung	TBC	Optional
> Infrarot	SEN0206, aushttps://www.dfrobot.com/product-1495.html	Temperatur	TBC	Optional
> Lautsprecher	 	 	Erfolgreich	Aus Arduino kit
> LIDAR	 	Abstandsmessung	TBC	 
> RGB LED Modul	KY-016	Anzeige	TBC	Optional

Habe obenstehende Tabelle geupdatet. Passt das so für @all? Dann wäre das der Beschluss-Stand. Bitte bis 22.05. zurückmelden, falls etwas nicht passt. Ansonsten wird das Ticket geschlossen.

**Comment by mausausdruck1** [comment]
RFID für das Eis-Team.  Hat da jemand Daten dazu?

**Comment by MatteoOPD** [comment]
Alle Sensoren sind in der Liste vorhanden. Wird ins WIKI übertragen. Issue wird geschlossen.
