### ISSUE TITLE
Application of Camera - define useful scenario

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#14]

**Comment by mausausdruck1** [comment]
kan ich machen... ich habe nur keine Rechte mich zu assignen...

**Comment by mausausdruck1** [comment]
[cam_apps.pdf](https://github.com/Denkschmied/fire-and-ice/files/3065389/cam_apps.pdf)

**Comment by Denkschmied** [comment]
Bitte ins Wiki verschieben
