### ISSUE TITLE
3D-Druck Teil Unterbau_Deckel bitte checken

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#23]
stl file besteht aus 2 objekten; eines davon ist so nicht druckbar (overhang) - bitte splitten

**Comment by fabioaufinger** [comment]
Habe es extra so aufgeteilt wie wir das das letzte Mal ausgemacht haben. Ich schaue es mir am Abend an, vielleicht ist mir ein Fehler unterlaufen.

**Comment by Denkschmied** [comment]
![image](https://user-images.githubusercontent.com/35607501/57703310-14d5ba80-7660-11e9-946f-763c8aedd41b.png)
In gelb markiert der Überstand - wenn ich von rechts nach links drucke (rechts unterste schicht), dann geht sich die nase nicht aus

**Comment by fabioaufinger** [comment]
Achso das ist nicht das Teil Unterbau_Deckel sondern Motorhalter. Wäre so gedacht gewesen, dass man die an der Kante aufstellt und die "Nase" mit Stützmaterial druckt. Bei mir im Cura ging es so.

**Comment by Denkschmied** [comment]
Schickst du mir bitte einen Screenshoot in Cura?
