### ISSUE TITLE
Treiber-Board Spec

### ISSUE THREAD

**Issue by mausausdruck1** [Denkschmied/fire-and-ice#24]
Wird ein neues Board entworfen, oder das aus Projekt 1 oder 2 verwendet? Wenn ersteres der Fall ist, wie sieht der Zeitplan aus? @Denkschmied

**Comment by Denkschmied** [comment]
Wir werden ein fertiges Board verwenden. Im Stile von https://www.reichelt.at/entwicklerboards-motodriver2-debo-motodriver2-p202829.html?PROVID=2788&gclid=Cj0KCQjww47nBRDlARIsAEJ34bnXL7yJTSwFsslczNWwKGQBRuRN06fiEkK6nVZUpP4TCrIKLb4wXPMaAmvhEALw_wcB&&r=1

**Comment by Denkschmied** [comment]
Hier kommt das finale Board:
https://www.conrad.at/de/p/entwickler-platine-sbc-motodriver2-arduino-banana-pi-cubieboard-pcduino-raspberry-pi-raspberry-pi-2-b-raspberry-1573541.html?ef_id=Cj0KCQjww47nBRDlARIsAEJ34bmS0T-gL1rZc5p9STetRc-nmbEg_X-jB6_hybyf-xu9t9la2r0aAwwaAj6iEALw_wcB:G:s&gclid=Cj0KCQjww47nBRDlARIsAEJ34bmS0T-gL1rZc5p9STetRc-nmbEg_X-jB6_hybyf-xu9t9la2r0aAwwaAj6iEALw_wcB
