### ISSUE TITLE
Assignment of IP addresses to robots

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#28]
**Ziel:**
Jeder Roboter hat eine eindeutige IP Adresse.

**Comment by fabioaufinger** [comment]
Bitte mich zuteilen. Ich kann das hier über die App gerade nicht machen.

**Comment by fabioaufinger** [comment]
Infos stehen jetzt in der Wiki unter Network drin.
Die IP-Adressen können jederzeit angepasst werden.
