### ISSUE TITLE
Python / MATLAB Code for US-sensor HC-SR04

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#29]
**Ziel:**
Funktionierender Python3 Code für den Sensor HC-SR04. Das Programm erfasst die Entfernung in cm zu einem Objekt.

**Comment by Denkschmied** [comment]
https://github.com/Denkschmied/fire-and-ice/wiki/Software

**Comment by fabioaufinger** [comment]
Auch hier siehe Wiki Code Snippets.
