### ISSUE TITLE
Python / MATLAB Code for RPM-Sensor

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#30]
**Ziel:**
Funktionierendes Programm, mit Ausgabe der Umdrehungen in 1/min.

Folgender Sensor wird verwendet werden:
http://anleitung.joy-it.net/?goods=speed-sensor

**Comment by Denkschmied** [comment]
https://github.com/Denkschmied/fire-and-ice/wiki/Software

**Comment by MatteoOPD** [comment]
Falk und ich haben uns Gedanken zum RPM Sensor (Umsetzung in Matlab) gemacht. Problem ist hierbei ggf. die Abtastfrequenz. Wenn es blöd läuft gehen uns Signale verloren da der Prozessor bzw. der Loop zu diesem Zeitpunkt gerade mit anderen Aufgaben beschäftigt ist.

Aus diesem Grund haben wir mal folgende Rechnung angestellt um die maximal benötigte Loop-Durchlaufzeit zu berechnen.

Bezeichnung | Wert
-- | --
Fahrgeschwindigkeit | 5 km/h
Fahrgeschwindigkeit | 1,39 m/s
Durchmesser Rad: 6 cm | 0,19 m
20 Löcher/U (Lochscheibe) | 7,37 U/s
Abtastfrequenz | 147 Hz
Nyquist | 295 Hz
Sicherheitsfaktor (2x RPM) | 590 Hz
Durchlaufzeit | 2 ms

**Comment by MatteoOPD** [comment]
Habe den Code nun hochgeladen. Hat jemand einen RPM und kann ihn mal ausprobieren? 
@daholzmichl : Du villeicht?
