### ISSUE TITLE
Pyhton / MATLAB Code for Stepper Motor 

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#32]
**Ziel:**
Funktionierendes Programm für den Schrittmotor vom Sensorset. Eingabe eines Winkels, Ausgabe des aktuellen Winkels.

**Comment by Denkschmied** [comment]
https://github.com/Denkschmied/fire-and-ice/wiki/Software

**Comment by MatteoOPD** [comment]
Mit Stepper Motor ist wahlweise auch der Servo gemeint, oder?

**Comment by MatteoOPD** [comment]
Ich gehe davon aus, dass der Code für die Antriebs-motoren gemeint sind und schließe das Ticket.
