### ISSUE TITLE
Python / MATLAB Code for DC motors

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#33]
**Ziel:**
Basissoftware für die Ansteuerung von DC-Motoren. Definierte Übergabe von Fahrparametern (Ein/Aus, Richtung, Geschwindigkeit).

**Comment by Denkschmied** [comment]
https://github.com/Denkschmied/fire-and-ice/wiki/Software

**Comment by fabioaufinger** [comment]
Auch hier siehe Wiki Code Snippets
