### ISSUE TITLE
Stromversorgung Raspberry-Pi über 5V GPIO und L298N H-Bridge

### ISSUE THREAD

**Issue by MatteoOPD** [Denkschmied/fire-and-ice#40]
Servus
ich habe gerade das Problem das mein Raspberry nicht starten kann mit der Stromversorgung über den Stihl-Akku (10,8V) --> H-Brücke L298N  (5V Jumer ist gesetzt) --> Raspberry Pi 5V GPIO.

Der RPi zeigt ein buntes Bild und versucht es dann wieder von vorne und sagt auch etwas von Stromversorgung...

Hatte jemand die Stromversorgung über denselben Pfad vor?

**Comment by daholzmichl** [comment]
Servus,

ich hab 6 von den DC/DC Wandler bestellt: https://www.amazon.de/dp/B077VW4BTY/ref=pe_3044161_185740101_TE_item, werde die sobald geliefert testen und Feedback geben. Ich bin natürlich bereit einige davon auszuleihen falls notwendig / möglich.

LG
Alex

**Comment by Denkschmied** [comment]
Klingt nach einer zu geringen Spannung...

**Comment by MatteoOPD** [comment]
Die haben wir gemessen. Das stellt eigentlich kein Problem dar. Jeder der die Möglichkeit hat noch eine Power-Bank zu nutzen sollte das tun, der Rest kann ggf. einen DC/DC-Wandler von Alex leihen!?

Vielleicht kann jeder kurz kommentieren welche Lösung er anstrebt, um ggf. noch Teile besorgen zu können:
- Amthor: => wenn geht, dcdc, sonst Powerbank. (fehlt mir beides)
- Gökmen --> Powerbank (liegt vor)
- Heigl
- Nocker --> DC/DC könnte auch auf die Powerbank gehen jedoch nichts in bestellliste geplant
- Oberloher  --> PowerBank (fehlt mir aber noch)
- Schafferer-->DC/DC, kann aber auch auf die Powerbank gehen
- Schröder
- Trocker
- Roth --> PowerBank (Liegt bereits vor)
- Sulzenbacher
- Aufinger --> DC/DC
- Hagen --> PowerBank (Liegt bereits vor)
- Maierhofer --> DC/DC (Liegt bereits vor)

**Comment by JoeUniv** [comment]
Ich kann leider noch immer nichts editieren, ich hab eine PowerBank.

**Comment by MatteoOPD** [comment]
@Denkschmied: Kannst Du bitte noch 3-4 PowerBanks mitbringen aus der FH, falls verfügbar? Danke!
