### ISSUE TITLE
Bitte Drehzahl-Code testen

### ISSUE THREAD

**Issue by MatteoOPD** [Denkschmied/fire-and-ice#41]
Ich habe leider keinen Drehzahl-Sensor. Bitte jemand den Code testen dem der Sensor vorliegt.
https://github.com/Denkschmied/fire-and-ice/issues/30

**Comment by mausausdruck1** [comment]
ich habe es getestet und es gab ein paar fehler, Ich habe es auch etwas umgebaut, heisst jetzt https://github.com/Denkschmied/fire-and-ice/blob/master/rpmread.py und ist für links getestet
