### ISSUE TITLE
Die haben wir gemessen. Das stellt eigentlich kein Problem dar. Jeder der die Möglichkeit hat noch eine Power-Bank zu nutzen sollte das tun, der Rest kann ggf. einen DC/DC-Wandler von Alex leihen!?

### ISSUE THREAD

**Issue by bobby-oh** [Denkschmied/fire-and-ice#42]
Die haben wir gemessen. Das stellt eigentlich kein Problem dar. Jeder der die Möglichkeit hat noch eine Power-Bank zu nutzen sollte das tun, der Rest kann ggf. einen DC/DC-Wandler von Alex leihen!?

Vielleicht kann jeder kurz kommentieren welche Lösung er anstrebt, um ggf. noch Teile besorgen zu können:
- Amthor: => wenn geht, dcdc, sonst Powerbank. (fehlt mir beides)
- Gökmen
- Heigl
- Nocker
- Oberloher --> PowerBank (fehlt mir aber noch)
- Schafferer-->DC/DC, kann aber auch auf die Powerbank gehen
- Schröder
- Trocker
- Roth --> PowerBank
- Sulzenbacher --> DC/DC
- Aufinger --> DC/DC
- Hagen --> PowerBank (Liegt bereits vor)
- Maierhofer --> DC/DC (Liegt bereits vor)

_Originally posted by @ampxtreme in https://github.com/Denkschmied/fire-and-ice/issues/40#issuecomment-498220182_

**Comment by MatteoOPD** [comment]
Ich weiß nicht wer das geschrieben hat, bitte keine Duplikate erstellen...
