### ISSUE TITLE
Configure Raspberry Pi for MATLAB

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#6]
Create check list for preparing Raspberry Pi to be used with MATLAB

**Comment by fabioaufinger** [comment]
@fabioaufinger

**Comment by mrc-gkmn** [comment]
Assign me too if additional help ist needed. :)

**Comment by MatteoOPD** [comment]
Everyone should do that at home. It´s way faster than in the FH! It took me 5 Minutes for the configuration of the Pi via Matlab. There is also a good tutorial for the Raspi-Addin.

**Comment by MatteoOPD** [comment]
Has everybody done this? 
I have a little problem here. At home I can use the raspberry normal with matlab. But I can´t connect to any other network. 
Maybe someone could upload his working image of the Rasp. with working configuration? Then I can copy the data for everybody to their SD-Cards when needed.

**Comment by fabioaufinger** [comment]
The image of my Raspberry has 16GB in size. I think an upload is not recommended, we should exchange it in the next session in Kufstein with an USB device.

**Comment by MatteoOPD** [comment]
Really? I think the SD Card has 16 gig. But not the Raspberry. But yes we can also do it in the FH - if not everybody needs it, cause the SD cards are very slow.
