### ISSUE TITLE
Testing of sensors

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#7]
Test different sensors with Raspberry Pi (MATLAB, Python)

**Comment by MatteoOPD** [comment]
I will Do this. Cant See where to assign this Task to myself (Using Smartphone).

**Comment by JoeUniv** [comment]
johannes Heigl (damit mein account mal dabei ist)

**Comment by MatteoOPD** [comment]
Testing of flame sensor finished. No problems so far. Range: ca. 1m+ in front of the sensor. With angle to the side (~75°) approx. 20 cm.

Ultrasonic sensors are working. Radar application should be a single topic in my opinion. 

--> Finished.
