### ISSUE TITLE
Order sensors

### ISSUE THREAD

**Issue by Denkschmied** [Denkschmied/fire-and-ice#8]

**Comment by nico45** [comment]
Mache ich.

**Comment by bobby-oh** [comment]
Bettina kommentiert.

**Comment by nico45** [comment]
[Ordering of Sensors - Fire and Ice.pdf](https://github.com/Denkschmied/fire-and-ice/files/3076610/Ordering.of.Sensors.-.Fire.and.Ice.pdf)

**Comment by nico45** [comment]
Task erledigt. Werde die Datei auch zusätzlich in Wiki einfügen. 
Das ist mein Vorschlag an Sensoren die gekauft werden könnten mit den dazu gehörigen Links und Preisen.
Bei zusätzlich benötigten Ergänzungen bitte melden Thomas (@Denkschmied )

VG
Nico

**Comment by nico45** [comment]
FYI @Denkschmied

**Comment by Denkschmied** [comment]
Muss die Issue noch mal öffnen: Bei den Sensoren brauche ich bitte noch die Stückzahl. Bei den Anbietern am Besten auf Reichelt, Mouser oder Conrad ausweichen - Ebay und sonstige Hersteller sind leider nicht möglich (aus Abrechnungstechnischen Gründen).

**Comment by nico45** [comment]
[Ordering of Sensors 2 - Fire and Ice.pdf](https://github.com/Denkschmied/fire-and-ice/files/3102993/Ordering.of.Sensors.2.-.Fire.and.Ice.pdf)

**Comment by nico45** [comment]
Anbei das Angebot von den jeweils billigsten Anbieter der Sensoren. Habe Reichelt, Mouser und Conrad untereinander abgeglichen.
VG
Nico

**Comment by nico45** [comment]
@Denkschmied bei benötigten Ergänzungen bitte wieder melden :)
